config/routes.rb
Rails.application.routes.draw do
 resources :announcements
resources :comments
resources :tasks do
resources :comments

resources :sessions
devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
root 'projects#index'

  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
        match '/sessions/user.new', to: 'devise/sessions#create', via: :post

end
devise_scope :user do
  get "sign_in", to: "devise/sessions#new"
end

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"

resources :teams
resources :sprints
resources :notifications

resources :projects do

  resources :tasks
  resources :sprints
   resources :announcements
  resources :sprints do
    resources :tasks
  end
  resources :tasks
  resources :sprints
  resources :teams do
    resources :users do
      member do
        get 'add_user_to_team'
      end
    end
  end

root 'projects#index'

  resources :users
end

resources :tasks
resources :sprints
resources :teams
resources :users
resources :notifications
resources :sessions

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"

  match 'add_task_to_user_task_user' => 'users#add_task_to_user', :as =>'add_task_to_user',via: [:get, :post]

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base

	has_one :project

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
  @project = Project.find(params[:project_id])
  @announcements = @project.announcements
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  # Create a new announcement inside a specific project.
  def create
  @project = Project.find(params[:project_id])
  @announcement = @project.announcements.new(announcement_params)

  respond_to do |format|
  if @announcement.save
  format.html { redirect_to project_path(@project), notice: 'Announcement was successfully created.' }
  format.json { render :show, status: :created, location: @announcement }
  else
  format.html { render :new }
  format.json { render json: @announcement.errors, status: :unprocessable_entity }
  end
end
end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
		# Update the attributes of the announcement.
	  def update
	 	respond_to do |format|
		  if @announcement.update(announcement_params)
		    format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
		    format.json { render :show, status: :ok, location: @announcement }
		  else
		    format.html { render :edit }
		    format.json { render json: @announcement.errors, status: :unprocessable_entity }
 end
		end
	  end

	  # DELETE /announcements/1
	  # DELETE /announcements/1.json
	 	# Delete an unwanted announcement.
	  def destroy
		  @announcement.destroy
	 	 respond_to do |format|
		  format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
		  format.json { head :no_content }
		end
	  end

	  private
		# Use callbacks to share common setup or constraints between actions.
		def set_announcement
		  @announcement = Announcement.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
	 # Only input the parameters of the sprint which is the announcement body.
		def announcement_params
		  params.require(:announcement).permit(:announcement)
		end
	end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= simple_form_for(@announcement) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :announcement %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/announcements/_new.html.erb
<h1>New Announcement</h1>

<%= form_for([@project, @project.announcements.build]) do |f| %>

<div class="field">
  <%= f.label :announcement %><br>
  <%= f.text_field :text %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/announcements/_show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="small-20 large-10 columns">
<p>
<p>
  <strong>Announcement:</strong>
  <%= @announcement.announcement %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Announcements</h1>

<table>
  <thead>
    <tr>
      <th>Announcement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.announcement %></td>
        <td><%= link_to 'Show', announcement %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Announcement', new_announcement_path %>

app/views/announcements/new.html.erb
<h1>New Announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="small-20 large-10 columns">
<p>
  <strong>Announcement:</strong>
  <%= @announcement.announcement %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>