config/routes.rb
Rails.application.routes.draw do
 resources :announcements
resources :comments
resources :tasks do
resources :comments

resources :sessions
devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
root 'projects#index'

  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
        match '/sessions/user.new', to: 'devise/sessions#create', via: :post

end
devise_scope :user do
  get "sign_in", to: "devise/sessions#new"
end

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"

resources :teams
resources :sprints
resources :notifications

resources :projects do

  resources :tasks
  resources :sprints
   resources :announcements
  resources :sprints do
    resources :tasks
  end
  resources :tasks
  resources :sprints
  resources :teams do
    resources :users do
      member do
        get 'add_user_to_team'
      end
    end
  end

root 'projects#index'

  resources :users
end

resources :tasks
resources :sprints
resources :teams
resources :users
resources :notifications
resources :sessions

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"

  match 'add_task_to_user_task_user' => 'users#add_task_to_user', :as =>'add_task_to_user',via: [:get, :post]

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :sprint
	belongs_to :project
	has_many :comments
	validates_presence_of :deadline
	belongs_to :user
	belongs_to :team
	belongs_to :user
	 attr_accessor :assignee

## Heba
## gets the user assigned name assigned to the task by tasking the task_id
def self.finduser(taskid)
getid = Task.find(taskid).user_id
if getid == nil
	assignee = "No Assignee"
 else 
  assignee = User.find(getid).username
end
end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json

  # tasks are sorted by their status by default.
  # added some extra sorting features, you can sort by title, priority.....etc
  # If a specific sprint is chosen, only the tasks in this sprint will appear
  # sorted ascendingly by their deadline.
  def index
    @tasks = Task.find_by_sql("SELECT * FROM tasks ORDER BY CASE status
                                                            WHEN '' THEN 1
                                                            WHEN 'in progress' THEN 2
                                                            WHEN 'reviewing' THEN 3
                                                            WHEN 'done' THEN 4 END")
    @sortType = params[:sort]

    if @sortType == "title"
      @tasks = Task.find_by_sql("SELECT * FROM tasks ORDER BY title ASC")
    end

    if @sortType == "status"
      @tasks = Task.find_by_sql("SELECT * FROM tasks ORDER BY CASE status
                                                            WHEN '' THEN 1
                                                            WHEN 'in progress' THEN 2
                                                            WHEN 'reviewing' THEN 3
                                                            WHEN 'done' THEN 4 END")
    end

    if @sortType == "description"
      @tasks = Task.find_by_sql("SELECT * FROM tasks ORDER BY description ASC")
    end

    if @sortType == "deadline"
      @tasks = Task.find_by_sql("SELECT * FROM tasks ORDER BY deadline ASC")
    end


    if @sortType == "story_points"
      @tasks = Task.find_by_sql("SELECT * FROM tasks ORDER BY story_points ASC")
    end

    if @sortType == "priority"
      @tasks = Task.find_by_sql("SELECT * FROM tasks ORDER BY CASE priority
                                                              WHEN '' THEN 1
                                                              WHEN 'high' THEN 2
                                                              WHEN 'medium' THEN 3
                                                              WHEN 'low' THEN 4 END")
    end
    @project = Project.find(params[:project_id])
    @sprint = Sprint.find(params[:sprint_id])
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @project = Project.find(params[:project_id])
    @task = @project.tasks.build
  end

  # GET /tasks/1/edit
  def edit
    @project = Project.find(params[:project_id])
  end

  # POST /tasks
  # POST /tasks.json
  # Create a new task in a certain sprint inside a project.
  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @project, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  # Update the attributes of a task.
  def update
    @project = Project.find(params[:project_id])

    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @project, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  # Delete an unwanted task.
  def destroy
    @sprint = Sprint.find(params[:sprint_id])
    @project = Project.find(params[:project_id])

    @task.destroy
    respond_to do |format|
      format.html { redirect_to @project, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
@project = Project.where(id: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :status, :priority, :story_points, :deadline )
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/Task.new.html.erb
<%= render 'form' %> <%= link_to 'Back', tasks_path %> 

app/views/tasks/_form.html.erb
<%= form_for([@project, @task]) do |f| %>

<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</div>
<div class="field">
  <%= f.label :status %><br>
  <%= f.text_field :status %>
</div>
<div class="field">
  <%= f.label :priority %><br>
  <%= f.text_field :priority %>
</div>
<div class="field">
  <%= f.label :story_points %><br>
  <%= f.text_field :story_points %>
</div>
<div class="field">
  <%= f.label :deadline %><br>
  <%= f.date_select :deadline %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/tasks/_show.html.erb
<strong>Title:</strong>
  <%= @task.title %>
</p>
</div>
</div>
<div class="row">
  <div class="small-10 large-8 columns">

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>
</div>
</div>
<div class="row">
  <div class="small-10 large-8 columns">
<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>
</div>
</div>
<div class="row">
  <div class="small-10 large-8 columns">
<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>
</div>
</div>
<div class="row">
  <div class="small-10 large-8 columns">
<p>
  <strong>Story points:</strong>
  <%= @task.story_points %>
</p>
</div>
</div>
<div class="row">
  <div class="small-10 large-8 columns">
<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>
</div>
</div>
</div>
<%= link_to 'Edit', edit_project_task_path(@project, @task) %>
  <H4>Comments</H4>
<div id="comments">
<%= render :partial => @task.comments %>
</div>
<%= simple_form_for [@task, Comment.new] do |f| %>
<p>

<%= f.input :body, :label => "New Comment", as: :text, input_html: { rows: "3" } %>
</p>
<p><%= f.submit "Add Comment", class: "btn btn-primary" %></p>
<% end %> 
</div>
</div>

app/views/tasks/_task.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= task.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= task.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= task.priority %>
</p>

<p>
  <strong>Story points:</strong>
  <%= task.story_points %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= task.deadline %>
</p>

app/views/tasks/delete.html.erb
<% if !flash[:notice].blank? %>
	<div>
		<%= flash[:notice] %>
	</div>
	<% end %>

<div>
<h2>Delete Project</h2>

<%= form_for(:task, :url => {:action => 'destroy', :id => @task.id}) do |f| %>

<p>Are you sure you want to delete this project ?</p>
	
	<p><%= @task.title %></p>

<div>
	<%= submit_tag("delete task") %>
</div>

<%end%>

</div>

app/views/tasks/edit.html.erb
<h4>Edit Task</h4>

<%= render 'form' %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<h1> Tasks</h1>

<table>
  <thead>
    <tr>
      <th><%= link_to("Title", {:sort => 'title'}) %></th>
      <th><%= link_to("Description", {:sort => 'description'}) %></th>
      <th><%= link_to("Status", {:sort => 'status'}) %></th>
      <th><%= link_to("Priority", {:sort => 'priority'}) %></th>
      <th><%= link_to("Story points", {:sort => 'story_points'}) %></th>
      <th><%= link_to("Deadline", {:sort => 'deadline'}) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <% if task.user_id ==nil %>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= task.story_points %></td>
        <td><%= task.deadline %></td>

        <td><%= link_to 'Show', project_sprint_tasks_path(@project, @sprint) %></td>
        <td><%= link_to 'Edit', edit_project_sprint_task_path(@project, @sprint, task) %></td>
        <td><%= link_to 'Destroy',  project_sprint_task_path(@project, @sprint, task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Assign Task', {:controller => 'users', :action => 'index', :id => task.id, :sprint => @sprint.id, :project => @project.id} %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<br>


<%= link_to 'New Task', new_project_sprint_task_path %>

app/views/tasks/index.json.html.erb
json.array!(@posts) do |post|
  json.extract! task, :id, :title, :body
  json.url task_url(task, format: :json)
end

app/views/tasks/new.html.erb
<h4>New Task</h4>

<%= render 'form' %>

app/views/tasks/show.htmk.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <h1 class="text-center">
    <%= @task.title %>
    <% if current_user.id == @task.user.id %>
      <small><%= link_to 'Edit', edit_task_path(@post) %></small>
    <% end %>
  </h1>
</div>

<br><br><br>

<div class="row">
  <div class="small-10 large-8 columns">
    <h6>
      <i class="fa fa-calendar-o"> <span><%= @post.created_at.strftime('%d %b %Y') %></span></i>&nbsp; &nbsp;
      <i class="fa fa-user"> <span><%= User.user_name(@task.user) %></span></i>&nbsp; &nbsp;
      <i class="fa fa-tags"> <span><%= @task.category %></span></i>
    </h6>
  </div>
  <div class="large-4 columns text-right">
      <h6 class="text-right">share on social media</h6>
  </div>
</div>
<br>
<%=@post.body%>



<div class="row">
    <h4>Comments</h4>
    <% @task.comments.each do |comment| %>
      <hr>
      <div class="row">
        <div class="small-10 large-8 columns">
          <h6>
            <i class="fa fa-user"> <span><%= User.user_name(comment.user) %></span></i>
            <i class="fa fa-calendar-o"> <span><%= comment.created_at.strftime('%d %b %Y') %></span></i>
          </h6>
        </div>
      </div>
      <%= comment.body %>
    <% end %>
</div>

<br><br>

<div class="row">
  <h3>Add a comment:</h3>
  <%= form_for([@task, @task.comments.build]) do |f| %>
      <%= f.text_area :body %>
      <%= f.submit %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<strong>Title:</strong>
  <%= @task.title %>
</p>
</div>
</div>
<div class="row">
  <div class="small-10 large-8 columns">

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>
</div>
</div>
<div class="row">
  <div class="small-10 large-8 columns">
<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>
</div>
</div>
<div class="row">
  <div class="small-10 large-8 columns">
<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>
</div>
</div>
<div class="row">
  <div class="small-10 large-8 columns">
<p>
  <strong>Story points:</strong>
  <%= @task.story_points %>
</p>
</div>
</div>
<div class="row">
  <div class="small-10 large-8 columns">
<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<p>
  <strong>Assignee:</strong>
  <%= @assignee %>
</p>

</div>
</div>
<%= link_to 'Edit', edit_project_task_path %>
</div>

app/views/tasks/show.js.erb
console.log ("GO FUCK YOURSELF")
$('#task-view').hide(0);
$('#task-view').html("<%= j (render 'show') %>");
$('#task-view').show(0);