config/routes.rb
Rails.application.routes.draw do
 resources :announcements
resources :comments
resources :tasks do
resources :comments

resources :sessions
devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
root 'projects#index'

  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
        match '/sessions/user.new', to: 'devise/sessions#create', via: :post

end
devise_scope :user do
  get "sign_in", to: "devise/sessions#new"
end

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"

resources :teams
resources :sprints
resources :notifications

resources :projects do

  resources :tasks
  resources :sprints
   resources :announcements
  resources :sprints do
    resources :tasks
  end
  resources :tasks
  resources :sprints
  resources :teams do
    resources :users do
      member do
        get 'add_user_to_team'
      end
    end
  end

root 'projects#index'

  resources :users
end

resources :tasks
resources :sprints
resources :teams
resources :users
resources :notifications
resources :sessions

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"

  match 'add_task_to_user_task_user' => 'users#add_task_to_user', :as =>'add_task_to_user',via: [:get, :post]

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  has_many :sprints
  has_many :teams
  has_many :announcements

  validates :title, presence: true
  attr_accessor :sprint_array


  # def tasks
  #   tasks_array = []
  #   tasks_array << sprints.map(&:tasks)
  #   tasks_array.flatten
  # end

  ## Heba
## returns the most close deadline of the sprint by tasking the projectid
  def self.recentdeadline(projectid) 
sprint_array =Sprint.where(:project_id => projectid).order(:deadline).first
sprint_array = sprint_array.deadline
end



end

app/controllers/projects_controller.rb
  class ProjectsController < ApplicationController
    before_action :set_project, only: [:show, :edit, :update, :destroy]

    include ProjectsHelper
    # GET /projects
    # GET /projects.json

    #No users yet ,so sorting is done project wises
    #First a sort of all the critical tasks is done in the project individually "tempproject = project.tasks.sort { |a,b| a.deadline <=> b.deadline }"
    #then they are all appended in a list *of critical tasks* to be sorted according to deadline
    # You retrieve All the the projects, so the 'Index' view can use them.
    def index
      @projects = []
      for project in Project.all do
        if project.isPrivate
          if current_user != nil
            if isAdmin(current_user) or canView(current_user, project)
              @projects.push(project)
            end
          end
        else
          @projects.push(project)
        end
      end

      @criticaltasks = []
      if @projects != nil
        @projects.each do |project|
        tempproject = project.tasks.sort { |a,b| a.deadline <=> b.deadline }
        @criticaltasks += tempproject if tempproject
      end
        @criticaltasks = @criticaltasks.sort { |a,b| a.deadline <=> b.deadline }
      else
        @sentence = "Yaaay you have no critical tasks"
      end
    end

  # GET /projects/1
    # GET /projects/1.json
    # views a project that was clicked on only if the project is not private or if the user is the admin or logged in.
    # otherwise it prints a  message "you don't have permissions to view this project" 
    def show
      @showProject = true

      if @project.isPrivate
        if current_user == nil or !(isAdmin(current_user) or canView(current_user, project))
          @sentence = "You don't have permissions to view this project"
          @showProject = false
        end
      end
    end

    # GET /projects/new
    # you create a new project
    def new
      @project = Project.new
    end

    # GET /projects/1/edit
    # you edit the project that you clicked on.
    def edit
    end

    # POST /projects
    # POST /projects.json
    # takes the information that you wrote on the form and uses it to create a project and saves it in the Database.
    def create
        @project = Project.new(project_params)
        respond_to do |format|
        if @project.save
          format.html { redirect_to @project, notice: 'Project was successfully created.' }
          format.json { render :show, status: :created, location: @project }
        else
          format.html { render :new }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /projects/1
    # PATCH/PUT /projects/1.json
    # you update the form that you filled after you created the project.
    def update
      respond_to do |format|
        if @project.update(project_params)
          format.html { redirect_to @project, notice: 'Project was successfully updated.' }
          format.json { render :show, status: :ok, location: @project }
        else
          format.html { render :edit }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /projects/1
    # DELETE /projects/1.json
    # you delete the project from the Database.
    def destroy
        @project.destroy
        respond_to do |format|
        format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
    def set_project
        @project = Project.find(params[:id])
    end

      # those parameters are the ones that the user can enter.
      # added the :isPrivate parameter to specify if the project is private or not.
    def project_params
        params.require(:project).permit(:title, :description, :deadline, :isPrivate)
    end
  end

app/helpers/projects_helper.rb
module ProjectsHelper
	def isAdmin(user)
	  return user.isAdmin
	end

	def canView(user, project)
	  for team in project.teams do
	    for member in team.users do
	      if member.email == user.email
	        return true
	      end
	    end
	  end

	  return false

	end
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :isPrivate %><br>
    <%= f.check_box :isPrivate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/delete.html.erb
<% if !flash[:notice].blank? %>
	<div>
		<%= flash[:notice] %>
	</div>
	<% end %>

<div>
<h2>Delete Project</h2>

<%= form_for(:project, :url => {:action => 'destroy', :id => @project.id}) do |f| %>

<p>Are you sure you want to delete this project ?</p>
	
	<p><%= @project.title %></p>

<div>
	<%= submit_tag("delete Project") %>
</div>

<%end%>

</div>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="row">
  <div class="small-6 medium-8 large-8 small-center large-centered columns">
    <div class="container-box">
      <!-- left part -->
      <div class="object-box">
        <div class="utility-box text-center">
          <h4>
            <%= link_to new_project_path do %>
            Add Project <i class="fa fa-plus-circle"></i>
            <% end %>
          </h4>
        </div>
        <% @projects.each do |project| %>
        <ul class="text-center">
          <li class="small-box">
            <h4><%= link_to project.title, project %></h4>
          </li>
        </ul>
        <% end %>
      </div>
      <!-- end of left part -->
      <!-- right part -->
      <div class="object-box">
        <div class="utility-box">
          <h4><%= link_to 'New Project', new_project_path %></h4>
        </div>
        <% @projects.each do |project| %>
        <ul class="text-center">
          <li class="small-box">
            <h4><%= link_to project.title, project %></h4>
          </li>
        </ul>
        <% end %>
      </div>
      <!-- end of right part -->
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
		<p id="notice"><%= notice %></p>
		<div class="row">

		  <div class="small-10 large-8 columns">
		<p>
		  <strong>Title:</strong>
		  <%= @project.title %>
		</p>
		</div>
		</div>
		<div class="row">
		  <div class="small-10 large-8 columns">
		<p>
		  <strong>Description:</strong>
		  <%= @project.description %>
		</p>
		</div>
		</div>
		<div class="row">
		  <div class="small-10 large-8 columns">
		<p>
		  <strong>Deadline:</strong>
		  <%= @project.deadline %>
		</p>
		</div>
		</div>

		<%= link_to 'Edit', edit_project_path(@project) %>
	
		<br><br>	

		<div class="row">
		  <div class="sprint">
			<ul>
			  <% @project.sprints.each do |sprint| %>
				<li>
				  <a>
				    <%= link_to sprint.number, project_sprint_path(@project, sprint) %>
				  </a>
				</li>
			  <% end %>
			</ul>
		  </div>
		</div>

		<br>	
		<style>
	.rectangle {
	  background: #0080FF;
	  color: white;
	  display: block;
	  border-width: 3px;
	  border-style: solid;
	  border-color: #0080FF;
	}
	h4.white
	{
		color: white;
	}
	</style>
		<div class="rectangle">
			<ul>
			  <% @project.announcements.each do |announcement| %>
				<h4 class = "white">   
				<%= announcement.announcement %>
				</h4>
			  <% end %>
			</ul>
		</div>

		<h1> New Team </h1>
		<%= form_for([@project, @project.teams.build]) do |f| %>
		<div class="field">
		  <%= f.label :name %><br>
		  <%= f.text_field :name %>
		</div>

		<div class="actions">
		  <%= f.submit %>
		</div>
		<% end %>

		<h1> New Announcement </h1>
		<%= form_for([@project, @project.announcements.build]) do |f| %>
		  <p>
			<%= f.label :announcement %><br>
			<%= f.text_field :announcement %>
		  </p>
		  <p>
			<%= f.submit %>
		  </p>
		<% end %>

		<%= render 'sprints/new' %>

<div class="row">
  <div class="small-4 small-left columns">
    <h2><%= @project.title %> <small><%= @project.description %></small></h2>
    <h5><%= @project.deadline.strftime('Deadline:  %d %b %y, %I:%M %p')  %></h5>
    <%= link_to 'Edit', edit_project_path %>
  </div>
  <div class="small-4 small-right columns ">
    <h5>
      Teams:
      <% @project.teams.each do |team| %>
        <%= link_to team.name, project_team_path(@project, team) %> |
      <% end %>
      <%= link_to 'Add', new_project_team_path(@project) %>
    </h5>
    <h5>
      Sprints:
      <% @project.sprints.each do |sprint| %>
        <%= link_to sprint.number, project_sprint_path(@project, sprint) %> |
      <% end %>
      <%= link_to 'Add', new_project_sprint_path(@project) %>
    </h5>
  </div>
</div>
<hr/>


<style style="text/css">

.lcdstyle{
background-color:black;
color:yellow;
font: bold 18px MS Sans Serif;
padding: 3px;
}

.lcdstyle sup{
font-size: 80%
}

</style>

<script type="text/javascript">

function cdtime(container, targetdate){
if (!document.getElementById || !document.getElementById(container)) return
this.container=document.getElementById(container)
this.currentTime=new Date()
this.targetdate=new Date(targetdate)
this.timesup=false
this.updateTime()
}

cdtime.prototype.updateTime=function(){
var thisobj=this
this.currentTime.setSeconds(this.currentTime.getSeconds()+1)
setTimeout(function(){thisobj.updateTime()}, 1000)
}

cdtime.prototype.displaycountdown=function(baseunit, functionref){
this.baseunit=baseunit
this.formatresults=functionref
this.showresults()
}

cdtime.prototype.showresults=function(){
var thisobj=this


var timediff=(this.targetdate-this.currentTime)/1000
if (timediff<0){
this.timesup=true
this.container.innerHTML=this.formatresults()
return
}
var oneMinute=60
var oneHour=60*60
var oneDay=60*60*24
var dayfield=Math.floor(timediff/oneDay)
var hourfield=Math.floor((timediff-dayfield*oneDay)/oneHour)
var minutefield=Math.floor((timediff-dayfield*oneDay-hourfield*oneHour)/oneMinute)
var secondfield=Math.floor((timediff-dayfield*oneDay-hourfield*oneHour-minutefield*oneMinute))
if (this.baseunit=="hours"){
hourfield=dayfield*24+hourfield
dayfield="n/a"
}
else if (this.baseunit=="minutes"){
minutefield=dayfield*24*60+hourfield*60+minutefield
dayfield=hourfield="n/a"
}
else if (this.baseunit=="seconds"){
var secondfield=timediff
dayfield=hourfield=minutefield="n/a"
}
this.container.innerHTML=this.formatresults(dayfield, hourfield, minutefield, secondfield)
setTimeout(function(){thisobj.showresults()}, 1000)
}

function formatresults(){
if (this.timesup==false){
var displaystring=arguments[0]+" days "+arguments[1]+" hours "+arguments[2]+" minutes "+arguments[3]+" seconds left until the deadline."
}
else{
var displaystring = "The deadline has passed!"
}
return displaystring
}

function formatresults2(){
if (this.timesup==false){
var displaystring="<span class='lcdstyle'>"+arguments[0]+" <sup>days</sup> "+arguments[1]+" <sup>hours</sup> "+arguments[2]+" <sup>minutes</sup> "+arguments[3]+" <sup>seconds</sup></span> left until the deadline."
}
else{
var displaystring = "The deadline has passed!"
alert("The project is due!")
}
return displaystring
}

</script>

<div id="countdowncontainer"></div>
<br />

<script type="text/javascript">

var year = "<%= h @project.deadline.strftime("%Y") -%>"
var month = "<%= h @project.deadline.strftime("%-m") -%>"
var day = "<%= h @project.deadline.strftime("%d") -%>"
var date = month + " " + day + ", "
var deadline = new cdtime("countdowncontainer",date + year + " 23:59:59")
deadline.displaycountdown("days", formatresults2)

</script>

<div class="row">

  <div class="small-10 large-8 columns">

<strong><%= @sentence %></strong>

<% if @showProject %>
<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>
</div>
    <p>
      <strong>Title:</strong>
      <%= @project.title %>
    </p>
  </div>
</div>
<div class="row">
  <div class="small-10 large-8 columns">
<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>
</div>
</div>
<div class="row">
  <div class="small-10 large-8 columns">
<p>
  <strong>Deadline:</strong>
  <%= @project.deadline %>
</p>
</div>
</div>


<br><br>

<%= form_for([@project, @project.teams.build]) do |f| %>
<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>


<h1>New Announcement</h1>

   


<div class="actions">
  <%= f.submit %>
</div>
<% end %>

<br>

<hr/>
<div class="row">
  <div class=" large-8 small-centered columns">
    <div class ="panel-box" >

</head>
<body>

<table style="width:100%" cellspacing=0 cellpadding =0>
  <col align="left">
  <col align="left">
  <col align="right">
  <tr bgcolor='#939BBA'>
    <td><font color='#FFFFFF'><font size="4">Total Story Points</font></font></td>
    <td><font color='#FFFFFF'><font size="4"> </font></font></td>
    <td><font color='#FFFFFF'><font size="4">Deadline</font></font></td>
    <td bgcolor='#939BBA' ></td>
  </tr>
  <tr >
    <td bgcolor='#939BBA'><font size="5">< @user.points%></font></td>
    <td bgcolor='#939BBA'><font size="5"></font></td>
    <% if @deadline == nil %>
    <% @deadline = 'No Sprint Deadlines' %>
    <% else %>
        <td bgcolor='#939BBA'><font size="5"><%= @deadline %></font></td>
        <% end %>
             <td bgcolor='#939BBA' ><font color='#FFFFFF'><font size="2">performance -> </font></font></td>
  </tr>
</table>     
      </div>
      </div>
      </div>


<div class="row">
  <div class="small-6 medium-8 large-8 small-centered large-centered columns">
    <div class="container-box">

      <!-- left part -->
      <div class="object-box">
        <div class="utility-box text-center">
          <h4>
            <%= link_to new_project_task_path(@project) do %>
            Add task <i class="fa fa-plus-circle"></i>
            <% end %>
          </h4>
        </div>
        <% @project.tasks.each do |task| %>
        <ul class="text-center">
          <li class="small-box">
            <h4><%= link_to task.title, project_task_path(@project, task) %></h4>
          </li>
        </ul>
        <% end %>
      </div>
      <!-- end of left part -->
      <!-- right part -->
      <div class="object-box">
        <div class="utility-box text-center">
          <h4>
            text text text
          </h4>
        </div>
        <div class="text-center">
          <h4>Task info should be displayed here ..</h4>
        </div>
        <div id="task-view" class="text-center" style="display:none;">aa</div>
      </div>
      <!-- end of right part -->
    </div>
  </div>
</div>



<% end %>


<br>

<br>

<%= render 'sprints/new' %>

app/views/projects/statistics.html.erb
<h2>Statistics Page</h2>

<div class="row">
    <div class="6-large columns">
        <%= high_chart("my_id", @chart) %>
    </div>
</div>